Issue 38 msg clean up
smarc-project/smarc2 pull request #50
Opened 2024-11-04 17:07 UTC by tko-dev

## smarc2 Changes
[Issue Ticket](https://github.com/smarc-project/smarc2/issues/38)
Refactoring the following messages from `sam_msg` -> `smarc_msg`:
- [x] `Leak`
- [x] `PercentStamped`
- [x] `LightCommand`
	- Generic enough that it can be used across vehicles
		-  [Legacy Dependencies](https://github.com/search?q=org%3Asmarc-project%20LIghtCommand&type=code)
		- Change impacts: `sam_drivers`, `sam_common`
- [x] `LightCommandArray`
	- Generic enough that it can be used across vehicles
		- Change impacts: same as above

Removing the following unused messages:
- `smarc_msg`
  - [x] `StringPair`
    -  https://github.com/search?q=org%3Asmarc-project%20StringPair&type=code
    - Only found in new code but has no usage in entire repo besides defintion
  - [x] `ExecutionStatus`
    - https://github.com/search?q=org%3Asmarc-project+ExecutionStatus&type=code
    - Found in legacy code, primarily used in legacy planning code

Evaluated but **not** removed/refactored messages. Could be updated or moved if willing to refactor upstream/downstream code.
- `smarc_msg`
  - `DualThrusterFeedback` : utilized by sam_auv_drivers
  - `DualThrusterRPM` : utilized by sam_auv_drivers
- `sam_msg`
  - `BallastAngles`: utilized across older code in SMaRC org, could refactor if we are willing to update dependencies
	  - https://github.com/search?q=org%3Asmarc-project+BallastAngles&type=code
  - `CircuitStatus*`: utilized across older code in SMaRC org, could refactor to `smarc_msgs` as is generic enough to apply to any AUV / UAV.
	  - https://github.com/search?q=org%3Asmarc-project%20CircuitStatus&type=code

## SMARCUnityAssets Updates
MR changes require refactoring of `SMARCUnityAssets` which is captured on the following [MR](https://github.com/smarc-project/SMARCUnityAssets/pull/83)

2024-11-06 09:40 UTC, tko-dev commented on messages/sam_msgs/CMakeLists.txt
> +  "msg/Links.msg"
Just moved messages for better readability (not actually added)

2024-11-06 09:40 UTC, tko-dev commented on examples/sam_basic_controllers/src/pid_utils/pid_actuator_trim.cpp
Updated basic controller C++ imports to ensure controller keeps working with all refactoring

2024-11-06 10:25 UTC, tko-dev commented on examples/sam_basic_controllers/package.xml
>    <depend>std_msgs</depend>
Need to remove all but std_msgs

2024-11-06 10:41 UTC, KKalem requested changes

2024-11-06 10:41 UTC, KKalem commented on messages/sam_msgs/CMakeLists.txt
>    "action/SystemsCheck.action"
nuke

2024-11-06 10:41 UTC, KKalem commented on examples/sam_basic_controllers/package.xml
> +  <depend>smarc_msgs</depend>
nuke

2024-11-06 10:41 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "srv/LatLonToUTMOdometry.srv"
nuke

2024-11-06 10:41 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/ControllerStatus.msg"
double check

2024-11-06 10:41 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/CTD.msg"
nuke

2024-11-06 10:41 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/LatLonOdometry.msg"
nuke

2024-11-06 10:41 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/LatLonStamped.msg"
nuke

2024-11-06 10:41 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/SMTask.msg"
nuke

2024-11-06 10:41 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/StringArray.msg"
nuke

2024-11-06 10:41 UTC, KKalem commented on simulation/SMARCUnityAssets
plz

2024-11-11 09:42 UTC, KKalem requested changes
last small bits

2024-11-11 09:42 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/SMTask.msg"
Nuke this with the script

2024-11-11 09:42 UTC, KKalem commented on messages/smarc_msgs/CMakeLists.txt
>    "msg/StringArray.msg"
this too

2024-11-11 09:47 UTC, KKalem commented
Also nuking https://github.com/smarc-project/smarc2/blob/758d90a26c60b7d167248274a26d60c44da35917/gui/smarc_nodered/src/waraps_bridge.py#L5 while we're at it.

2024-11-11 10:24 UTC, tko-dev commented
Sim is happy, hit all the waypoints with a simple small test

2024-11-12 09:53 UTC, KKalem approved these changes

2024-11-12 09:54 UTC, merged